# Use postgres/example user/password credentials
version: '2.10'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: hu1
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
