version: '2.10'
services:
  web1:
    image: nginx 
    volumes:
      - ./web1:/usr/share/nginx/html 
  web2:
    image: nginx 
    volumes:
      - ./web2:/usr/share/nginx/html
  proxy:
    image: nginx 
    volumes:
      - ./proxy-conf:/etc/nginx/conf.d
    ports:
      - 80:80
